<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dzlzaf99h/image/upload/v1554376585/79819a35-130b-4c67-877a-cc51f588e1fc.png" alt="Mark Essien">
                        <h6>Samuel Bello</h6>
                        <p>UI Designer</p>
                        <ul class="list">
                           <li><a href="twitter.com/thesamuelbello" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="github.com/samuelbello" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="medium.com/@thesamuelbello" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>LI’m a UI designer, passionate about building usable and functional products that give the user an exceptional experience, optimizes business value, and makes a real difference in the world.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Design | Prototyping | Research</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
